-- Traffic-Predictor: create traffic and event tables
-- Run this in Supabase SQL Editor or via MCP apply_migration / execute_sql
-- Matches schema of traffic.csv and event.csv

-- Traffic table: congestion-level data per location and time
CREATE TABLE IF NOT EXISTS traffic (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id INTEGER NOT NULL,
  traffic_timestamp TIMESTAMPTZ NOT NULL,
  traffic_date DATE NOT NULL,
  congestion_level INTEGER NOT NULL CHECK (congestion_level >= 1 AND congestion_level <= 10)
);

-- Event table: event-level data per location and time
CREATE TABLE IF NOT EXISTS event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id INTEGER NOT NULL,
  event_type TEXT NOT NULL,
  event_name TEXT NOT NULL,
  event_date DATE NOT NULL,
  event_timestamp TIMESTAMPTZ NOT NULL,
  event_duration INTEGER NOT NULL DEFAULT 60
);

-- Optional: indexes for common filters and joins
CREATE INDEX IF NOT EXISTS idx_traffic_location_date ON traffic (location_id, traffic_date);
CREATE INDEX IF NOT EXISTS idx_traffic_timestamp ON traffic (traffic_timestamp);
CREATE INDEX IF NOT EXISTS idx_event_location_date ON event (location_id, event_date);
CREATE INDEX IF NOT EXISTS idx_event_type ON event (event_type);

-- Optional: enable Row Level Security (RLS) and add policies if you need per-user access later
-- ALTER TABLE traffic ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE event ENABLE ROW LEVEL SECURITY;
